# Generated by Django 5.1.1 on 2024-10-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_image',
            field=models.ImageField(blank=True, null=True, upload_to='actor_image/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.DateField(default=0),
        ),
    ]
