# Generated by Django 5.1.1 on 2024-10-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_moments_movie_moments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
